global:
  scrape_interval: 1s
  evaluation_interval: 1s
  external_labels:
    monitor: 'prometheus'

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'udapeople'
    ec2_sd_configs:
      - region: us-east-1
        access_key: XXXXXXXXXX
        secret_key: XXXXXXXXXXXXXXXXXXXXX
        port: 9100

rule_files:
  - /etc/prometheus/rules.yml

alerting:
  alertmanagers:
    - static_configs:
        - targets:
            - localhost:9093
