AWSTemplateFormatVersion: '2010-09-09'
Description: Deploys a Linux server in a public subnet.

Parameters:
  EnvironmentName:
    Description: An environment name that will be prefixed to resource names
    Type: String

  VpcCIDR:
    Description: Please enter the IP range (CIDR notation) for this BolaVPC
    Type: String
    Default: 10.0.0.0/16

  BolaPublicSN1CIDR:
    Description: Please enter the IP range (CIDR notation) for the public subnet in the first Availability Zone
    Type: String
    Default: 10.0.0.0/24

  BolaPublicSN2CIDR:
    Description: Please enter the IP range (CIDR notation) for the public subnet in the second Availability Zone
    Type: String
    Default: 10.0.1.0/24

  BolaPublicSN3CIDR:
    Description: Please enter the IP range (CIDR notation) for the public subnet in the second Availability Zone
    Type: String
    Default: 10.0.2.0/24

  BolaAMI:
    Description: Please enter the AMI for Launch Configuration
    Type: String

Resources:
  # Networking
  BolaVPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: !Ref VpcCIDR
      EnableDnsHostnames: true
      Tags:
        - Key: Name
          Value: !Ref EnvironmentName

  BolaInternetGW:
    Type: AWS::EC2::InternetGateway
    Properties:
      Tags:
        - Key: Name
          Value: !Ref EnvironmentName

  BolaVPCGatewayAttach:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      InternetGatewayId: !Ref BolaInternetGW
      VpcId: !Ref BolaVPC

  BolaPublicSN1:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref BolaVPC
      AvailabilityZone: !Select [0, !GetAZs '']
      CidrBlock: !Ref BolaPublicSN1CIDR
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Name
          Value: !Sub ${EnvironmentName} Public Subnet (AZ1)

  BolaPublicSN2:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref BolaVPC
      AvailabilityZone: !Select [1, !GetAZs '']
      CidrBlock: !Ref BolaPublicSN2CIDR
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Name
          Value: !Sub ${EnvironmentName} Public Subnet (AZ2)

  BolaPublicSN3:
    Type: AWS::EC2::Subnet
    Properties:
      VpcId: !Ref BolaVPC
      AvailabilityZone: !Select [2, !GetAZs '']
      CidrBlock: !Ref BolaPublicSN3CIDR
      MapPublicIpOnLaunch: true
      Tags:
        - Key: Name
          Value: !Sub ${EnvironmentName} Public Subnet (AZ3)

  BolaNatGW1EIP:
    Type: AWS::EC2::EIP
    DependsOn: BolaVPCGatewayAttach
    Properties:
      Domain: vpc

  BolaNatGW2EIP:
    Type: AWS::EC2::EIP
    DependsOn: BolaVPCGatewayAttach
    Properties:
      Domain: vpc

  BolaNatGW3EIP:
    Type: AWS::EC2::EIP
    DependsOn: BolaVPCGatewayAttach
    Properties:
      Domain: vpc

  BolaNatGW1:
    Type: AWS::EC2::NatGateway
    Properties:
      AllocationId: !GetAtt BolaNatGW1EIP.AllocationId
      SubnetId: !Ref BolaPublicSN1

  BolaNatGW2:
    Type: AWS::EC2::NatGateway
    Properties:
      AllocationId: !GetAtt BolaNatGW2EIP.AllocationId
      SubnetId: !Ref BolaPublicSN2

  BolaNatGW3:
    Type: AWS::EC2::NatGateway
    Properties:
      AllocationId: !GetAtt BolaNatGW3EIP.AllocationId
      SubnetId: !Ref BolaPublicSN3

  BolaPublicRT:
    Type: AWS::EC2::RouteTable
    Properties:
      VpcId: !Ref BolaVPC
      Tags:
        - Key: Name
          Value: !Sub ${EnvironmentName} Public Routes

  DefaultPublicRoute:
    Type: AWS::EC2::Route
    DependsOn: BolaVPCGatewayAttach
    Properties:
      RouteTableId: !Ref BolaPublicRT
      DestinationCidrBlock: 0.0.0.0/0
      GatewayId: !Ref BolaInternetGW

  BolaPublicSN1RouteTableAssociation:
    DependsOn: BolaNatGW1
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref BolaPublicRT
      SubnetId: !Ref BolaPublicSN1

  BolaPublicSN2RouteTableAssociation:
    DependsOn: BolaNatGW2
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref BolaPublicRT
      SubnetId: !Ref BolaPublicSN2

  BolaPublicSN3RouteTableAssociation:
    DependsOn: BolaNatGW3
    Type: AWS::EC2::SubnetRouteTableAssociation
    Properties:
      RouteTableId: !Ref BolaPublicRT
      SubnetId: !Ref BolaPublicSN3

  # Security Groups and Roles
  BolaWebServerSG:
    DependsOn: BolaVPCGatewayAttach
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Allow http to our hosts and SSH from local only
      VpcId: !Ref BolaVPC
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 80
          ToPort: 80
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 8080
          ToPort: 8080
          CidrIp: 0.0.0.0/0
        - IpProtocol: tcp
          FromPort: 22
          ToPort: 22
          CidrIp: 0.0.0.0/0
      SecurityGroupEgress:
        - IpProtocol: tcp
          FromPort: 0
          ToPort: 65535
          CidrIp: 0.0.0.0/0
      Tags:
        - Key: Name
          Value: !Sub ${EnvironmentName} WebServerSecurityGroup
        - Key: Description
          Value: !Sub ${EnvironmentName} Web Server Security Group

  BolaWebAppLaunchTemplate:
    Type: AWS::EC2::LaunchTemplate
    Properties:
      LaunchTemplateName: BolaWebAppLaunchTemplate
      LaunchTemplateData:
        UserData:
          Fn::Base64: !Sub |
            #!/bin/bash
            apt-get update -y
            apt-get install awscli -y
        ImageId: !Ref BolaAMI
        SecurityGroupIds:
          - !GetAtt BolaWebServerSG.GroupId
        InstanceType: t2.nano
        BlockDeviceMappings:
          - DeviceName: '/dev/sdk'
            Ebs:
              VolumeSize: 5
        KeyName: udacity_key

  BolaEC21:
    DependsOn: BolaPublicSN1RouteTableAssociation
    Type: AWS::EC2::Instance
    Properties:
      SubnetId: !Ref BolaPublicSN1
      LaunchTemplate:
        LaunchTemplateName: BolaWebAppLaunchTemplate
        Version: !GetAtt BolaWebAppLaunchTemplate.LatestVersionNumber
      Tags:
        - Key: Name
          Value: UdaDemo1
        - Key: Purpose
          Value: WebServerGroup
        - Key: Project
          Value: Udacity

Outputs:
  BolaVPC:
    Description: A reference to the created VPC
    Value: !Ref BolaVPC
    Export:
      Name: !Sub ${EnvironmentName}-VPCID

  # VPCBolaPublicRT:
  #   Description: Public Routing
  #   Value: !Ref BolaPublicRT
  #   Export:
  #     Name: !Sub ${EnvironmentName}-PUB-RT

  BolaPublicSN1:
    Description: A reference to the public subnet in the 1st Availability Zone
    Value: !Ref BolaPublicSN1
    Export:
      Name: !Sub ${EnvironmentName}-PUB1-SN

  BolaPublicSN2:
    Description: A reference to the public subnet in the 2nd Availability Zone
    Value: !Ref BolaPublicSN2
    Export:
      Name: !Sub ${EnvironmentName}-PUB2-SN

  BolaPublicSN3:
    Description: A reference to the public subnet in the 2nd Availability Zone
    Value: !Ref BolaPublicSN3
    Export:
      Name: !Sub ${EnvironmentName}-PUB3-SN

  PublicSubnets:
    Description: A list of the public subnets
    Value:
      !Join [',', [!Ref BolaPublicSN1, !Ref BolaPublicSN2, !Ref BolaPublicSN3]]
    Export:
      Name: !Sub ${EnvironmentName}-PUB-NETS

  BolaWebServerSG:
    Description: A reference to the web server security group that allows http to our hosts and SSH from local only
    Value: !Ref BolaWebServerSG
    Export:
      Name: !Sub ${EnvironmentName}-WS-SG
